export const SET_REDIRECT_ON_AUTH = 'SET_REDIRECT_ON_AUTH';

export const AUTHED_USER = 'AUTHED_USER';
export const AUTHING_USER = 'AUTHING_USER';
export const AUTHFAILED_USER = 'AUTHFAILED_USER';
export const UNAUTH_USER = 'UNAUTH_USER';


export const USER_NODES_FETCHED = 'USER_NODES_FETCHED';
export const USER_NODES_FETCHING = 'USER_NODES_FETCHING';
export const USER_NODES_INVALID = 'USER_NODES_INVALID';
export const USER_NODES_FETCH_FAILED = 'USER_NODES_FETCH_FAILED';
export const SELECT_USER_NODE = 'SELECT_USER_NODE';