export const SET_REDIRECT_ON_AUTH = 'SET_REDIRECT_ON_AUTH';

export const AUTHED_USER = 'AUTHED_USER';
export const AUTHFAILED_USER = 'AUTHFAILED_USER';
export const UNAUTH_USER = 'UNAUTH_USER';


export const USER_NODES_FETCHED = 'USER_NODES_FETCHED';
export const USER_NODES_FETCHING = 'USER_NODES_FETCHING';
export const USER_NODES_FETCH_FAILED = 'USER_NODES_FETCH_FAILED';
export const SELECT_USER_NODE = 'SELECT_USER_NODE';


export const MQTT_CONNECT_CMD = 'MQTT_CONNECT_CMD';
export const MQTT_CONNECTED = 'MQTT_CONNECTED';
export const MQTT_DISCONNECT_CMD = 'MQTT_DISCONNECT_CMD';
export const MQTT_DISCONNECTED = 'MQTT_DISCONNECTED';
export const MQTT_SEND_CMD = 'MQTT_SEND_CMD';



export const NODE_SETTINGS_CREATING = 'NODE_SETTINGS_CREATING';
export const NODE_SETTINGS_CREATED = 'NODE_SETTINGS_CREATEED';
export const NODE_SETTINGS_CREATE_FAILED = 'NODE_SETTINGS_CREATE_FAILED';


export const PROVISIONING_SELECT_NETWORK = 'PROVISIONING_SELECT_NETWORK';
export const PROVISIONING_SET_PSK = 'PROVISIONING_SET_PSK';
export const PROVISIONING_SSID_FETCHED = 'PROVISIONING_SSID_FETCHED';

export const PROVISIONING_NETWORKS_LIST_FETCHING = 'PROVISIONING_NETWORKS_LIST_FETCHING';
export const PROVISIONING_NETWORKS_LIST_FETCH_FAILED = 'PROVISIONING_NETWORKS_LIST_FETCH_FAILED';
export const PROVISIONING_NETWORKS_LIST_FETCHED = 'PROVISIONING_NETWORKS_LIST_FETCHED';

export const PROVISIONING_SYSINFO_FETCHING = 'PROVISIONING_SYSINFO_FETCHING';
export const PROVISIONING_SYSINFO_FETCHED = 'PROVISIONING_SYSINFO_FETCHED';
export const PROVISIONING_SYSINFO_FETCH_FAILED = 'PROVISIONING_SYSINFO_FETCH_FAILED';

export const PROVISIONING_TEST_CREDS_SENDING = 'PROVISIONING_TEST_CREDS_SENDING';
export const PROVISIONING_TEST_CREDS_SEND_FAILED = 'PROVISIONING_TEST_CREDS_SEND_FAILED';
export const PROVISIONING_TEST_CREDS_SENT = 'PROVISIONING_TEST_CREDS_SENT';
