export const SET_REDIRECT_ON_AUTH = 'SET_REDIRECT_ON_AUTH';

export const AUTHED_USER = 'AUTHED_USER';
export const AUTHING_USER = 'AUTHING_USER';
export const AUTHFAILED_USER = 'AUTHFAILED_USER';
export const UNAUTH_USER = 'UNAUTH_USER';


export const USER_NODES_FETCHED = 'USER_NODES_FETCHED';
export const USER_NODES_FETCHING = 'USER_NODES_FETCHING';
export const USER_NODES_INVALID = 'USER_NODES_INVALID';
export const USER_NODES_FETCH_FAILED = 'USER_NODES_FETCH_FAILED';
export const SELECT_USER_NODE = 'SELECT_USER_NODE';


export const MQTT_CONNECT_CMD = 'MQTT_CONNECT_CMD';
export const MQTT_CONNECTED = 'MQTT_CONNECTED';
export const MQTT_DISCONNECT_CMD = 'MQTT_DISCONNECT_CMD';
export const MQTT_DISCONNECTED = 'MQTT_DISCONNECTED';
export const MQTT_SEND_CMD = 'MQTT_SEND_CMD';